import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./header";
import { SideBar } from "./sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <SideBar />
        <div>
          {children}
        </div>
        {/* <main className="h-full flex flex-col">
          
          <div className="flex-auto flex h-full">
            
            
          </div>
        </main> */}
      </body>
    </html>
  );
}
